version: '3.1'
services:
    mysql-service:
        container_name: myapp-mysql
        image: 'mysql:5.7'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "Matrimonial_App_Database"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
        ports:
            - 3306:3306
    spring:
        build: 
            context: .
        container_name: myapp-spring
        volumes:
            - .:/app
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mysql-service