FROM openjdk:11
COPY ./target/com.example.demo.-0.0.1-SNAPSHOT.jar com.example.demo.-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","com.example.demo.-0.0.1-SNAPSHOT.jar"]
#FROM openjdk:8-jdk-alpine
#EXPOSE 8080
#COPY target/myapp.jar /usr/app/
#WORKDIR /usr/app
#CMD ["java", "-jar", "myapp.jar"]